FROM openjdk:17-jdk-alpine
COPY build/libs/VPNconServer*SNAPSHOT.jar vpncon.jar
COPY ./init.sh init.sh
RUN chmod 777 init.sh
ENV SERVER_URL ${SERVER_URL}
ENV SERVER_PORT ${SERVER_PORT}
ENV DB_PORT ${DB_PORT}
ENV ROOT_NAME ${ROOT_NAME}
ENV ROOT_PASSWORD ${ROOT_PASSWORD}
ENV TOKEN_SECRET_KEY ${TOKEN_SECRET_KEY}
ENV CORS_ALLOWED_ORIGINS ${CORS_ALLOWED_ORIGINS}
ENV TG_USER_PASSWORD ${TG_USER_PASSWORD}
ENV ACCOUNTANT_USER_PASSWORD ${ACCOUNTANT_USER_PASSWORD}
ENV QIWI_SECRET_KEY ${QIWI_SECRET_KEY}
ENV QIWI_PUBLIC_KEY ${QIWI_PUBLIC_KEY}
ENTRYPOINT ["./init.sh"]