app:
  kafka:
    topic: subscription_updates

spring:
  profiles:
    active:
      - "prod"
      - "default"
  application:
    name: sms
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jackson:
    time-zone: UTC
    property-naming-strategy: SNAKE_CASE


kafka:
  producer:
    enable: true
    bootstrapServers: ${BOOTSTRAP_SERVERS}
    clientId: sms
    acksMode: all
    deliveryTimeout: 60s
    lingerMs: 12_000
    batchSize: 100_000
    maxInFlightPerConnection: 5
    enableIdempotence: true
    topic:
      name: subscription_updates
      partitions: 1
      replicas: 1

springdoc:
  swagger-ui:
    path: "/swagger-ui"

server:
  port: ${SERVER_PORT}

logging:
  config: classpath:log4j2-plain.xml


management:
  endpoints:
    web:
      base-path: "/"
      exposure:
        include: info, health, prometheus
      path-mapping:
        prometheus: "metrics"
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true
  server:
    port: ${MANAGEMENT_PORT}