CREATE TABLE subscription (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    role VARCHAR(255) NOT NULL,
    price_in_rub INT NOT NULL,
    peers_available INT NOT NULL,
    duration_days INT NOT NULL
);

CREATE TABLE user_subscription (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    subscription_id BIGINT NOT NULL REFERENCES subscription(id) ON DELETE CASCADE,
    expiration_day DATE NOT NULL
);