--CREATE TABLE mails (
--    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--    for_all BOOLEAN NOT NULL,
--    is_checked BOOLEAN NOT NULL,
--    time_stamp TIMESTAMP NOT NULL,
--    user_id BIGINT,
--    payload text NOT NULL,
--    CONSTRAINT user_id_null_check_rule CHECK (for_all IS FALSE)
--);
CREATE TABLE reminders (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    reminder_type VARCHAR NOT NULL,
    is_checked BOOLEAN NOT NULL,
    day_stamp DATE NOT NULL,
    user_id BIGINT,
    payload text,
    CONSTRAINT user_id_reminder_type_time_stamp UNIQUE (user_id, reminder_type, day_stamp)
);